export const actionTypes = {
  FETCH_PRODUCTS : 'FETCH_PRODUCTS',
  
  FETCH_PENDING: 'FETCH_PENDING',
  FETCH_FULFILLED: 'FETCH_FULFILLED',
  FETCH_ERROR: 'FETCH_ERROR',

  FETCH_SELECTED_PRODUCT : 'FETCH_SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT'
}