export const actionTypes = {
  FETCH_PENDING: 'FETCH_PENDING',
  FETCH_FULFILLED: 'FETCH_FULFILLED',
  FETCH_ERROR: 'FETCH_ERROR',

  FETCH_PRODUCTS : 'FETCH_PRODUCTS',

  FETCH_SELECTED_PRODUCT : 'FETCH_SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',

  ADD_PRODUCT_CART: 'ADD_PRODUCT_CART',
  REMOVE_PRODUCT_CART: 'ADD_PRODUCT_CART',
  INCREASE_QUANTITY_PRODUCT_CART: 'INCREASE_QUANTITY_PRODUCT_CART',
  DECREASE_QUANTITY_PRODUCT_CART: 'DECREASE_QUANTITY_PRODUCT_CART'
}